### ISSUE TITLE
Dash state ground correction fails to work

### ISSUE THREAD

**Issue by VampireFlower** [swoolcock/GravityHelper#20]
when youre in dash state, the game likes to drag madeline down to the ground if she's withing 2px of the ground, this is to make supers that dont start on the ground easier. this doesnt happen on the ceiling if youre inverted

normal:
https://user-images.githubusercontent.com/68222518/111123324-cf70c580-8534-11eb-90ea-4ac2c20716af.mp4

inverted:
https://user-images.githubusercontent.com/68222518/111123638-37bfa700-8535-11eb-9e3b-e4b4dabe16ea.mp4

related: madeline gets shoved 2px off the ground if shes in dash state while inverted, as this would make her hitbox flush with the ground if it wasnt adjusted like it currently is
https://user-images.githubusercontent.com/68222518/111123428-f202de80-8534-11eb-8d43-eb24d574c37b.mp4

**Comment by swoolcock** [comment]
Fixed.
