### ISSUE TITLE
Corner Corrections #2

### ISSUE THREAD

**Issue by VampireFlower** [swoolcock/GravityHelper#8]
having your dash intersect the 4 pixels of the edge of a ceiling corner corrects you, but this does not happen on floors while upside down

https://user-images.githubusercontent.com/68222518/109099722-c7b1c400-76e0-11eb-971f-0541e7a50bf5.mp4

**Comment by swoolcock** [comment]
Please test whether this is still a thing, I think it should be fixed.

**Comment by swoolcock** [comment]
Fixed.
