### ISSUE TITLE
Player can Dash Through an UpsideDownJumpThru attached to a FloatySpaceBlock

### ISSUE THREAD

**Issue by LozenChen** [swoolcock/GravityHelper#83]
Just up dash here, then there's chance that you can go through the jumpthru (with normal gravity), it seems this only happens when the jumpthru moves downward
![celeste](https://github.com/swoolcock/GravityHelper/assets/68326284/b58b515d-1538-4439-8298-b7fec45ef518)

**Comment by swoolcock** [comment]
Is this a Gravity Helper UDJT or the one from Maddie's Helping Hand?

**Comment by LozenChen** [comment]
that's from GravityHelper

**Comment by swoolcock** [comment]
Can you try doing that as two separate jumpthrus?  I'm wondering if it's breaking because the hitbox clips through the moon block.  In fact I'm almost certain that's why.

**Comment by LozenChen** [comment]
that fixes this issue
imo this should still be patched, as this kind of structure does appear in some mod maps (e.g. GalleryCollab heartside flag 6 -> flag5).
anyway, you are the one to make decision

**Comment by swoolcock** [comment]
Honestly I'd say it's lazy mapping, especially since Celeste incorrectly puts the "attach points" on either end of the jumpthru even though they don't actually attach to anything.

I'll see what I can do but I get the feeling it's going to be non-trivial, and it's low priority.

**Comment by swoolcock** [comment]
Okay, looks like this happens even if the jumpthru is attached "properly".  I'll take a look.

**Comment by swoolcock** [comment]
Fixed, will be in the next release.  <3
